export const tagMap = {
    global: [
        'funny',
        'reaction',
        'known player',
        'fail',
        'high skill',
        'smart / creative',
        'clutch',
        'teamwork',
        'wtf',
    ],
    genre: {
        shooter: [
            'flick',
            'headshot',
            'tracking',
            'sniper',
            'trigger discipline',
        ],
        tactical: ['ace'],
        moba: ['combo', 'ability plays', 'ult'],
        battleRoyale: [],
    },
    game: {
        valorant: [
            'lineup',
            'char.raze',
            'char.kayo',
            'char.astra',
            'char.breach',
            'char.brimstone',
            'char.cypher',
            'char.jett',
            'char.kayo',
            'char.killjoy',
            'char.omen',
            'char.phoenix',
            'char.reyna',
            'char.sage',
            'char.skye',
            'char.sova',
            'char.viper',
            'char.yoru',
        ],
        'apex-legends': [
            'movement',
            'arenas',
            '1v3',
            'wingman',
            'kraber',
            'char.bloodhound',
            'char.gibraltar',
            'char.lifeline',
            'char.pathfinder',
            'char.wraith',
            'char.bangalore',
            'char.caustic',
            'char.mirage',
            'char.octane',
            'char.wattson',
            'char.crypto',
            'char.revenant',
            'char.loba',
            'char.rampart',
            'char.horizon',
        ],
        'halo-infinite': [],
    },
};
