"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tagMap = void 0;
exports.tagMap = {
    global: [
        'funny',
        'reaction',
        'known player',
        'fail',
        'high skill',
        'smart / creative',
        'clutch',
        'wtf',
        'copyrighted',
    ],
    genre: {
        teamBased: ['teamwork'],
        shooter: [
            'flick',
            'headshot',
            'tracking',
            'sniper',
            'trigger discipline',
        ],
        tactical: ['ace'],
        moba: ['combo', 'ability plays', 'ult'],
        battleRoyale: [],
    },
    game: {
        valorant: [
            'lineup',
            'char.raze',
            'char.kayo',
            'char.astra',
            'char.breach',
            'char.brimstone',
            'char.cypher',
            'char.jett',
            'char.kayo',
            'char.killjoy',
            'char.omen',
            'char.phoenix',
            'char.reyna',
            'char.sage',
            'char.skye',
            'char.sova',
            'char.viper',
            'char.yoru',
        ],
        'apex-legends': [
            'movement',
            'arenas',
            '1v3',
            'wingman',
            'kraber',
            'char.bloodhound',
            'char.gibraltar',
            'char.lifeline',
            'char.pathfinder',
            'char.wraith',
            'char.bangalore',
            'char.caustic',
            'char.mirage',
            'char.octane',
            'char.wattson',
            'char.crypto',
            'char.revenant',
            'char.loba',
            'char.rampart',
            'char.horizon',
        ],
        'halo-infinite': [
            // Multi
            'double',
            'triple',
            'overkill',
            'killtacular',
            'killtrocity',
            'killamanjaro',
            'killtastrophe',
            'killpocalypse',
            'killionaire',
            // Sprees
            'killing frenzy',
            'running riot',
            'rampage',
            'nightmare',
            'boogeyman',
            'grim reaper',
            'demon',
            // Medals
            'perfection',
            'steaktacular',
            'kong',
            'harpoon',
            'back smack',
            'assassination',
            'stick',
            'nade shot',
            'mind the gap',
            'ballista',
            'splatter',
            'snipe',
            'pancake',
            'no scope',
            'pull',
            'hail mary',
            'cluster luck',
            'bulltrue',
            'whiplash',
            '360',
            'nuclear football',
            'return to sender',
            'ninja',
            'quigley',
            'remote detonation',
            'perfect',
            'combat evolved',
            'from the grave',
            'tbag',
        ],
    },
};
//# sourceMappingURL=tags.js.map